version: "3.8"

services:
  app:
    image: shortener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      - "uvicorn"
      - "shortener.api.app:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      # - "--reload"
      # - "--reload-delay=0.5"
      # - "--reload-dir=shortener"
      # - "--no-access-log"
      - "--loop"
      - "uvloop"
      # - "gunicorn"
      # - "-k"
      # - "uvicorn.workers.UvicornWorker"
      # - "-c"
      # - "gunicorn_config.py"
      # - "shortener.api.app:app"
    environment:
      - ENVIRONMENT=local
      - DEBUG=1
      - REDIS_URL=redis://redis/0
      - S3_ENDPOINT=http://s3:9000
      - S3_ACCESS_KEY=abcdefgh
      - S3_SECRET_KEY=abcdefgh
      - WEB_CONCURRENCY=5   # 2*CPU + 1
      # - LOAD_TEST=0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - redis
      - s3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./s3_storage:/data
    environment:
      - MINIO_ACCESS_KEY=abcdefgh
      - MINIO_SECRET_KEY=abcdefgh
    command: server /data
